name: Build and deploy Node.js app to Azure Web App - DevopsIntro

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: Main

    env:
      PRIMARY_CONNECTIONS_STRING: ${{ secrets.PRIMARY_CONNECTIONS_STRING }}
      PORT: ${{ secrets.PORT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build --if-present

      - name: Archive artifact for deployment (excluding node_modules)
        run: zip -r release.zip . -x "node_modules/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: release.zip

  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: node-app

    - name: unzip artifact for deployment
      run: unzip release.zip

    - name: Install dependencies
      run: npm install

    - name: Run linter
      run: npm run lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint
    environment: Main

    env:
      PRIMARY_CONNECTIONS_STRING: ${{ secrets.PRIMARY_CONNECTIONS_STRING }}
      PORT: ${{ secrets.PORT }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: unzip artifact for deployment
        run: unzip release.zip

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test --if-present

  deploy:
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'DevopsIntro'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_30A2F68765B843C1AD87C264081DF44D }}
          package: .
